name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cpp:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          sudo apt-get install --no-install-recommends clang-format-11 libboost-dev libmbedtls-dev ninja-build
          pip install meson
      - uses: actions/checkout@v2
      - name: check meson.build lists and code style
        run: |
          mk/update-list.sh
          mk/format-code.sh
          git diff --exit-code
      - name: build CLI programs
        run: |
          meson build -Dbuildtype=debug -Dwerror=true
          ninja -C build
  arduino:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - id: cores
        name: refresh Arduino cores
        run: |
          echo 'https://espressif.github.io/arduino-esp32/package_esp32_index.json' > ~/arduino-cores.txt
          arduino-cli version
          arduino-cli update --additional-urls "$(<~/arduino-cores.txt)"
          echo ::set-output name=d::$(sha256sum ~/.arduino15/package_*index.json | sha256sum | cut -d' ' -f1)
      - name: cache Arduino cores
        uses: actions/cache@v2
        with:
          path: ~/.arduino15/staging/packages
          key: cores-${{ steps.cores.outputs.d }}
      - name: install Arduino cores
        run: |
          arduino-cli core install esp32:esp32 --additional-urls "$(<~/arduino-cores.txt)"
          arduino-cli lib install NimBLE-Arduino
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: install dependencies
        run: |
          pip install esptool
      - uses: actions/checkout@v2
      - name: prepare Arduino libraries
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE PION
          mkdir NDNph esp8266ndn
          curl -fsLS https://github.com/yoursunny/NDNph/archive/${NDNPH_VERSION}.tar.gz | tar -C NDNph -xz --strip-components=1
          curl -fsLS https://github.com/yoursunny/esp8266ndn/archive/${ESP8266NDN_VERSION}.tar.gz | tar -C esp8266ndn -xz --strip-components=1
        env:
          NDNPH_VERSION: 22e703555503c2d534774064d9bb444ee8011cbf
          ESP8266NDN_VERSION: f4b532d11418eec392bbd1e02a18468245eb3270
      - name: compile examples
        run: |
          for F in $(find ./examples -name 'sample.*'); do
            [[ -f "${F/sample./}" ]] || cp "${F}" "${F/sample.//}"
          done
          for E in $(find ./examples -name '*.ino' -printf '%h\n'); do
            printf "\n----\033[1;35m Build %s \033[0m----\n" ${E##*/}
            arduino-cli compile -b esp32:esp32:esp32 --warnings more \
              --build-property 'build.partitions=noota_ffat' \
              --build-property 'upload.maximum_size=2097152' \
              $E
          done
  node:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        subdir:
          - ./extras/ca
          - ./extras/exp
    defaults:
      run:
        working-directory: ${{ matrix.subdir }}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - uses: actions/checkout@v2
      - run: corepack pnpm install
      - name: check code style
        run: |
          corepack pnpm lint
          git diff --exit-code
      - run: corepack pnpm typecheck
  go:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        subdir:
          - ./extras/pcapparse
    defaults:
      run:
        working-directory: ${{ matrix.subdir }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v2
      - run: go install ./cmd/pion-pcapparse
