name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          sudo apt-get install libboost-dev
          python -m pip install --upgrade pip
          pip install cmake meson ninja
      - name: install Mbed TLS
        run: |
          mkdir -p $HOME/mbedtls $HOME/mbedtls-build
          curl -sfL https://github.com/ARMmbed/mbedtls/archive/${MBEDTLS_VERSION}.tar.gz | tar -C $HOME/mbedtls -xz --strip-components=1
          cd $HOME/mbedtls-build
          cmake -G Ninja $HOME/mbedtls -DENABLE_PROGRAMS=0 -DENABLE_TESTING=0
          ninja
          sudo $(which ninja) install
        env:
          MBEDTLS_VERSION: v2.25.0
      - name: install NDNph
        run: |
          mkdir -p $HOME/NDNph
          curl -sfL https://github.com/yoursunny/NDNph/archive/${NDNPH_VERSION}.tar.gz | tar -C $HOME/NDNph -xz --strip-components=1
          cd $HOME/NDNph
          meson build -Dunittest=disabled -Dprograms=disabled
          ninja -C build
          sudo $(which ninja) -C build install
        env:
          NDNPH_VERSION: develop
      - uses: actions/checkout@v2
      - name: checkout Pesa/spake2-mbed
        uses: actions/checkout@v2
        with:
          repository: Pesa/spake2-mbed
          ref: 25af4f567b57dd8634050e77dcd8769d8cc8f306
          token: ${{ secrets.GH_PAT }}
          path: spake2-mbed
      - run: mk/update-vendor.sh
      - name: check meson.build lists and code style
        run: |
          mk/update-list.sh
          mk/format-code.sh
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - name: build CLI programs
        run: |
          meson build -Dbuildtype=debug -Dwerror=true
          ninja -C build
  arduino:
    runs-on: ubuntu-20.04
    steps:
      - uses: arduino/setup-arduino-cli@v1.1.1
      - name: install Arduino cores and libraries
        run: |
          arduino-cli version
          arduino-cli core update-index --additional-urls $ARDUINO_CORE_URI
          arduino-cli core install esp32:esp32 --additional-urls $ARDUINO_CORE_URI
          arduino-cli lib update-index
          arduino-cli lib install ArduinoUnit
        env:
          ARDUINO_CORE_URI: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install esptool
      - uses: actions/checkout@v2
      - name: checkout Pesa/spake2-mbed
        uses: actions/checkout@v2
        with:
          repository: Pesa/spake2-mbed
          ref: 25af4f567b57dd8634050e77dcd8769d8cc8f306
          token: ${{ secrets.GH_PAT }}
          path: spake2-mbed
      - run: mk/update-vendor.sh
      - name: link library
        run: |
          mkdir -p $HOME/Arduino/libraries
          cd $HOME/Arduino/libraries
          ln -s $GITHUB_WORKSPACE ndn-onboarding
          mkdir NDNph esp8266ndn
          curl -sfL https://github.com/yoursunny/NDNph/archive/${NDNPH_VERSION}.tar.gz | tar -C NDNph -xz --strip-components=1
          curl -sfL https://github.com/yoursunny/esp8266ndn/archive/${ESP8266NDN_VERSION}.tar.gz | tar -C esp8266ndn -xz --strip-components=1
        env:
          NDNPH_VERSION: develop
          ESP8266NDN_VERSION: develop
      - name: compile Arduino sketches
        run: |
          for F in $(find ./examples -name 'sample.*'); do
            [[ -f "${F/sample./}" ]] || cp "${F}" "${F/sample.//}"
          done
          for D in $(find ./examples -name '*.ino' -printf '%h\n'); do
            printf "\n---- \033[1;35mBuild $D\033[0m ----\n"
            arduino-cli compile -b $FQBN $D
          done
        env:
          FQBN: esp32:esp32:heltec_wifi_kit_32
  ca:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: actions/checkout@v2
      - run: npm install
        working-directory: ./extras/ca
      - name: check code style
        run: |
          npm run lint
          [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
        working-directory: ./extras/ca
      - run: npm run typecheck
        working-directory: ./extras/ca
